# appveyor file

# build version format
version: "{build}"

platform: x64

image: Visual Studio 2015

# Set a known clone folder
clone_folder: c:\projects\node-printer

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

environment:
  global:
    electron_version: 4.0.4
#   matrix:
#     # Node.js
#     - nodejs_version: "0.10"
#     - nodejs_version: "0.12"
#     - nodejs_version: "4.4"
#     - nodejs_version: "5.8"
#     - nodejs_version: "6.9"
#       build_electron: "true"

# matrix:
#   fast_finish: true
#   allow_failures:
#     - nodejs_version: "0.10"

# Get the latest stable version of Node 0.STABLE.latest
install:
  - ps: Install-Product node 10 x64
  - cmd: SET PATH=c:\python27;%PATH%
  - cmd: SET JOBS=4
  - cmd: SET BUILD_ONLY=true
  - npm install -g node-gyp node-pre-gyp
  - ps: ./tools/buildElectronWindows.ps1 $env:electron_version

build: OFF
test: OFF
deploy: OFF

artifacts:
  - path: 'build\stage\**\*.tar.gz'

branches:
  only:
    - master
